13682/framework implementation/konstantin
axelwarn2/sw-academy pull request #3
Opened 2024-08-02 10:09 UTC by axelwarn2

13682:Сделает разбиение реализованной верстки на соответствующие по смыслу отдельные файлы и подключит их все в нужном порядке в index.php
Реализация CRUD и валидации
Задача:  [13682](https://portal.sunweb.pro/company/personal/user/1214/tasks/task/view/13682/)

2024-08-02 12:58 UTC, nacretion requested changes

2024-08-02 12:58 UTC, nacretion commented on src/framework/Base/Models/Model.php
> +    public function save()
Типизация

2024-08-02 12:58 UTC, nacretion commented on src/framework/Base/Validators/ModelValidator.php
> +class ModelValidator
Нужно реализовать абстракный валидатор и User валидатор

2024-08-05 10:12 UTC, evgeny89 commented on src/framework/Base/Validators/Validator.php
> +            if (!preg_match(static::$rules[$rule], $data[$field])) {
регулярки не оптимальное решение... лучше использовать match где под каждую роль свое решение, например, метод обработчик для сложной логики (min для чисел и строк имеет разную логику, регулярки...), или для простых проверок тут в match валидация.

2024-08-05 10:52 UTC, merged